### ISSUE TITLE
IRF-read should handle *.asc files

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#4]
IRF -expected file should be a 1-dimensional ASCII file (T-axis). unless there is a reason. Not all IRF are sdt files. Conventionally its tab-delimited  *.asc file.

**Comment by Xanthorapedia** [comment]
This can be addressed in future development. The current system sees transients as coming from datasets and it takes some effort to adapt it to single transients.

**Comment by JenuC** [comment]
Most IRF that we handle in TCSPC labs are *.asc files. IRF-sdt is only an acquisition unit. One uses a single-pixel time-curve as IRF and not the whole image. This is because IRF is not distributed equally in an image. An image with urea crystal may have only 1 pixel that is from SHG and that is why I think we should handle .asc files ( even "instead" of sdt files).

**Comment by Xanthorapedia** [comment]
Are `.asc` files coming from raw `.sdt`'s? The UI allows you to select a single pixel from a `.sdt` file as the IRF. Is that sufficient? Or are you suggesting that the acquisition unit is doing the work and generating the `.asc` file?

**Comment by JenuC** [comment]
a) .asc file is just one-pixel time-curve written in ascii format. It is easy to modify on a notepad and is derived from the acquisition software(either SPCM or SPCimage). 
b) Maybe I can retry this on the UI after the manual is ready. I couldn't find a way to assign a single pixel for IRF. Maybe we should optionally display IRF with the fit so that the relative IRF position and shape can be evaluated before fitting dataset. 
c)The common format of handling IRF is as a single time curve than sdt file for SPCImage. Users can generate that during acquisition or on the FLIMJ UI as you suggest. But the .asc file should be saved so that it can be loaded at a later stage (instead of the full sdt).

**Comment by JenuC** [comment]
@Xanthorapedia  please upload/send_me an example *.asc file you used for enabling this feature. I can't make it work yet.  Find attached a sample IRF ASCII file I used.  
[IRF.txt](https://github.com/flimlib/flimj-ui/files/4893163/IRF.txt)

**Comment by JenuC** [comment]
I tried a single T-axis, tab-delimited transposed axis, and a few others. nothing worked out. maybe refer to this site: https://www.becker-hickl.com/faq/how-to-use-a-measured-irf-in-flim-analysis-in-spcimage/

**Comment by Xanthorapedia** [comment]
Just a single list of photon counts delimited by whitespace (space, tab, newline, etc.) like in their example should work. Are you on the newest version?

Your IRF should look like this if you remove the time column:
![image](https://user-images.githubusercontent.com/25558041/86972923-53b6b180-c139-11ea-8ada-ace71363fcc3.png)

**Comment by JenuC** [comment]
@Xanthorapedia : I like the way it looks. But please send me the modified file you used, so that I can test it on my end. It seems like I am missing something. My flimj-UI is current according to the FLIMJ-update site. Is there a different version on GitHub that I should try for this?

**Comment by JenuC** [comment]
I just tried with the flimj-ui-1,0.7 version on github. but i can't make the asc-loading to work. I tried with single column files with newline and whitespace separation. There is no error. i don't see the irf peak. that's all. I guess it would be easier for me if you could just send me the format that worked for you. at least i can rule out the file-format issue

**Comment by Xanthorapedia** [comment]
Can you try [this one](https://github.com/flimlib/flimj-ui/files/4914900/IRF.zip)? Make sure your file has `.asc` as extension and select "Show IRF Intensity" option.

**Comment by JenuC** [comment]
okay. so it was not the file format. it was the secret "show-irf- intensity" dropdown menu.  But now, I cannot see the IRF when the data file is loaded. I need to optimize the vertical bars/ fitting range based on where my IRF peak is. how can we fix that?

**Comment by Xanthorapedia** [comment]
The secret dropdown is documented in the manual. The default behavior is that if the IRF loading goes wrong, The error will be reported in the debug console. One improvement could be to automatically jump to "IRF Intensity" once an IRF is set. Shall we take that?

As for manually setting the ranges, any idea as to how to detect the peak boundary?

**Comment by JenuC** [comment]
One of the purposes of IRF is to decide if the lifetime-datafile file fitting-endpoints are justified or not. automatically feeding the IRF into the LMA/Bayes may cause errors if the shift between them is larger. And I think that we should not try to find peak/shift the IRF. It will add more confusion unless we add more controls for the user to adjust the _shift-position_. So I would say, the simplest solution is to let the green curve from the _IRF-dropdown_ menu stick even when that menu is back to _Intensity-mode._

**Comment by JenuC** [comment]
@Xanthorapedia : there is no changes to this feature.  The idea I mentioned is a way to see both lifetime and irf curve together in the plotting panel regardless of which pixel lifetime curve is drawn from. This step has a lot of practical purposes. The current version, we can do only irf or intensity. I suggest, to have a both lifetime curve and a "normalized IRF to the lifetime curve" plotted together? let me know what you think.

**Comment by Xanthorapedia** [comment]
@JenuC I think the problem is that the IRF and lifetime curve are so different in magnitude that plotting one dwarfs the other. But both are actually there. I'm experimenting with normalizing IRF before plotting (this screenshot is taken in IRF mode, I plotted IRF to have the same height as the data):
![image](https://user-images.githubusercontent.com/25558041/90298893-e5fd5400-de61-11ea-9089-b3aa822b02c1.png)

I also adjusted the way IRF is displayed in intensity mode if that makes more sense: The part of the green curve selected in the IRF mode is left-justified, and you can adjust the start cursor in IRF mode to shift the peak left and right (assuming there are enough leading zeros in the IRF).
![image](https://user-images.githubusercontent.com/25558041/90298327-e4cb2780-de5f-11ea-8aa5-bb360dbf73d7.png)


Please let me know if this would help.

**Comment by JenuC** [comment]
yeah. this looks good.  I tried to test it, but i cant get the UI to start with the current  build version
```code
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: flimlib/flimj/fitworker/FitWorker$FitEventHandler
	at flimlib.flimj.ui.FLIMJCommand.initFX(FLIMJCommand.java:134)
	at flimlib.flimj.ui.FLIMJCommand.lambda$run$0(FLIMJCommand.java:57)
	at flimlib.flimj.ui.FLIMJCommand.lambda$runAndWait$2(FLIMJCommand.java:96)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: flimlib.flimj.fitworker.FitWorker$FitEventHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
[WARNING] FLIMJ: UI init failed or aborted by user. Exiting.
```

**Comment by Xanthorapedia** [comment]
@JenuC Can you please try again now? Make sure to include the newly released [flimj-ops:2.1.0](https://maven.scijava.org/service/local/repositories/releases/content/flimlib/flimj-ops/2.1.0/flimj-ops-2.1.0.jar) if you are installing by copying jars. I will make a release and upload to the update site after this issue is closed.
